### ISSUE TITLE
Installation gotchas to be covered in the README

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-demos#21]
Here are a few things I stumbled over during the installation of Fractal at the FMI which we should cover in the updated READMEs.

1. The fractal user needs to have read & write access to the log & env folders. The users running jobs also need write access to the log folder & at least read access to the env folder.
Easiest way: Have the fractal-demos folder in a folder with broad permissions that is accessible to both `fractal` and the users, start the server from there with default log & env locations within that server folder

To go towards production, logs & envs will need to be in new places. Let's document how to set the necessary env variables (I think those are `FRACTAL_ROOT` and `RUNNER_ROOT_DIR`?)

2. Set the `RUNNER_CONFIG` correctly before running Fractal
For FMI, that means: `export RUNNER_CONFIG='fmi'`

For the future: How easy will it be for people that want to test Fractal to add RUNNER_CONFIG settings for their own cluster? Basically means modifying this part of the server, right? https://github.com/fractal-analytics-platform/fractal-server/blob/06676fe74bd514d3eaa58e3a84f8d7adae3f0195/fractal_server/app/runner/_parsl/_setup.py

3. Installing the envs does require significant space, ensure the space & tmp space is available
server + task env added up to 4.3 GB in this installation. But it also required > 1GB in tmp space for pypi. The default /tmp location on our VM had only 1GB of /tmp space. Thus, setting `TMPDIR` explicitly as the `fractal` user before starting the server was necessary. This can be done by:
`export TMPDIR=/PATH/TO/SOMEWHERE/WITH/SOME/GIGS/OF/SPACE` 

4. We may want to set the `HOME` variable in the run_example.sh file explicitly
It defaults to $HOME. Setting it to an explicit path on the share (e.g. on tungsten at FMI) may be more stable. I think only the user needs to be able to write there, is that correct?

**Comment by jluethi** [comment]
Actually, on 2: Would it make sense to be able to import future configs from a file? Then, a new place could "just" create the correct config file instead of having to change any Fractal server code

**Comment by tcompa** [comment]
> Actually, on 2: Would it make sense to be able to import future configs from a file? Then, a new place could "just" create the correct config file instead of having to change any Fractal server code

That would make sense.

Note that the new SLURM backend will be simpler to configure.
We may still want to have "executors", which will only be defined by the set of `(partition name, cpu requirements, memory requirements)` -- see https://github.com/fractal-analytics-platform/fractal-server/issues/278. For those executors, reading from a file is trivial.

**Comment by tcompa** [comment]
> Here are a few things I stumbled over during the installation of Fractal at the FMI which we should cover in the updated READMEs.
> 
>     1. The fractal user needs to have read & write access to the log & env folders. The users running jobs also need write access to the log folder & at least read access to the env folder.
>        Easiest way: Have the fractal-demos folder in a folder with broad permissions that is accessible to both `fractal` and the users, start the server from there with default log & env locations within that server folder
> 
> 
> To go towards production, logs & envs will need to be in new places. Let's document how to set the necessary env variables (I think those are `FRACTAL_ROOT` and `RUNNER_ROOT_DIR`?)
> 
>     2. Set the `RUNNER_CONFIG` correctly before running Fractal
>        For FMI, that means: `export RUNNER_CONFIG='fmi'`
> 
> 
> For the future: How easy will it be for people that want to test Fractal to add RUNNER_CONFIG settings for their own cluster? Basically means modifying this part of the server, right? https://github.com/fractal-analytics-platform/fractal-server/blob/06676fe74bd514d3eaa58e3a84f8d7adae3f0195/fractal_server/app/runner/_parsl/_setup.py
> 
>     3. Installing the envs does require significant space, ensure the space & tmp space is available
>        server + task env added up to 4.3 GB in this installation. But it also required > 1GB in tmp space for pypi. The default /tmp location on our VM had only 1GB of /tmp space. Thus, setting `TMPDIR` explicitly as the `fractal` user before starting the server was necessary. This can be done by:
>        `export TMPDIR=/PATH/TO/SOMEWHERE/WITH/SOME/GIGS/OF/SPACE`
> 
>     4. We may want to set the `HOME` variable in the run_example.sh file explicitly
>        It defaults to $HOME. Setting it to an explicit path on the share (e.g. on tungsten at FMI) may be more stable. I think only the user needs to be able to write there, is that correct?

I think (to be tested) that this was only to have a place where the parsl bash scripts are written (by the user), and `cd`-ing into HOME is a simple way to reach a folder where the user can write. This will most likely go away with the new SLURM executor.

**Comment by jluethi** [comment]
> Note that the new SLURM backend will be simpler to configure.
We may still want to have "executors", which will only be defined by the set of (partition name, cpu requirements, memory requirements) -- see https://github.com/fractal-analytics-platform/fractal-server/issues/278. For those executors, reading from a file is trivial.

Very good point. If we're anyway opening a slurm job per task & parallelization object (e.g. for each well-image that we apply illum_corr to), then we can even consider making this more granular, i.e. exposing CPU & mem options directly. But a set of predetermined executors may be an easy start :)

**Comment by jluethi** [comment]
I think these comments should all be covered now and the relevant environment variables are documented well now. Closing this issue, feel free to reopen.
