### ISSUE TITLE
[Diary] Installing Fractal locally (`process` backend)

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-demos#25]
I went through a local installation of fractal on my mac on macos Ventura 13.1 once with a process runner and I could successfully run through the installation, setting up a client, collecting the actual tasks and running example 01. Great to see that everything is running in this setup!

I'll briefly document here what I did, then follow it up with some high level discussion points where we can improve and some minor issues that I observed.

## Server installation
I installed a server environment by using the installation script here: https://github.com/fractal-analytics-platform/fractal-demos/tree/main/examples/server
`. ./install_script.sh`

I then started the server using a modified version of the `server_config_and_start.sh`: I changed the `FRACTAL_RUNNER_BACKEND` to `process` and removing the `FRACTAL_SLURM_CONFIG_FILE=config_uzh.json` from the env variable being set. The rest worked with the defaults.
`. ./server_config_and_start.sh`
(run this in a screen to have it running in the background)

## Client installation
I installed the client from the `01_cardio_tiny_dataset` example helper script. Everything executed below was in that environment:
`. ./install_client.sh`

I then ran the preliminary setup:
`. ./preliminary_setup.sh`

(and checked that the tasks would be collected successfully with `fractal task check-collection 1`)

## Running an example experiment
I ran the 01_cardio_tiny_dataset example which has its test data on zenodo. For that to work, one needs to install the zenodo_get library first into the client env:
`pip install zenodo_get`

Then:
`. ./fetch_test_data_from_zenodo.sh`

One can then either go through the project creation, dataset creation, workflow creation & submission one by one. Or run it all at once by running:
`. ./run_example.sh`

This should complete fairly quickly (submitting the script to it being finished took 30s on my machine). One can check the status with `fractal job show ID` (where the ID is the job ID of the submitted workflow, 1 for the first workflow submitted. This is shown when submitting the workflow) [syntax is changing to this soon, at the moment, it still was `fractal job status`]

## Open questions
In the preliminary setup, why do I need to provide a `SLURM_USER` when using a `process` runner? And what is the `SLURM_USER` variable used for in that case?

## Learnings
1. We should have a global "How to get started" with Fractal that is not per repo, e.g. on the [splash page here](https://fractal-analytics-platform.github.io) based on those demo scripts. If we add short READMEs to the demo scripts with what may need to be adapted, then the "How to get started" page could point to the server folder and e.g. the 01 example. And refer to the documentation for further details.
2. We should make sure to cover the option to use the `process` backend to run things locally, not just a `slurm` backend. The slurm backend is what we'll obviously use for deployments that need to scale, but for testing and to introduce people to Fractal, the local `process` runner that does not require a slurm setup is super helpful. The documentation can currently be slightly misleading here. i.e. the server [Install and deploy page](https://fractal-analytics-platform.github.io/fractal-server/install_and_deploy/) currently states having a SLURM client node as a requirement, while one can actually test Fractal without.

## Minor observation
a) Some links in the documentation are currently broken. e.g. the links to computational backends and Configuration are broken on this page: https://fractal-analytics-platform.github.io/fractal-server/install_and_deploy/. It does not seem to affect links to external resources like pypi though. They point to https://fractal-analytics-platform.github.io/configuration/ instead of https://fractal-analytics-platform.github.io/fractal-server/configuration/ (missing /fractal-server inbetween). Not sure whether this affects other parts as well.

**Comment by jluethi** [comment]
I have now updated the splash page with a "How to Get Started" section and added READMEs containing the relevant information contained here on how to run the example with the `process` backend.

**Comment by tcompa** [comment]
A few answers will follow..


> One can check the status with fractal job show ID (where the ID is the job ID of the submitted workflow, 1 for the first workflow submitted.

Note that ID is the job ID, not the workflow one. A job (technically called an `ApplyWorkflow` object, in the database) is created each time the workflow is applied, and for instance it also includes information on the I/O datasets.

> This is shown when submitting the workflow) [syntax is changing to this soon, at the moment, it still was fractal job status]

Updated in `fractal-client=1.0.0rc1

> In the preliminary setup, why do I need to provide a SLURM_USER when using a process runner? And what is the SLURM_USER variable used for in that case?

`SLURM_USER` is indeed optional on the server side, as it should be. There is a glitch on the client side, see https://github.com/fractal-analytics-platform/fractal/issues/404.

> a) Some links in the documentation are currently broken.

Thanks.


> Another question I had about the process runner:
> Given that I removed the FRACTAL_SLURM_CONFIG_FILE variable and thus didn't specify any executors anymore, how does the process runner handle "submitting" all the things locally? Will it always run all wells in parallel? Or always run sequentially? I'm wondering whether a power user could set up Fractal on a powerful workstation using the process executor and how larger experiments would then be processed.

`FRACTAL_SLURM_CONFIG_FILE` only matters for the SLURM backend, as the variable name says ;)
The `process` backend directly submits all tasks (in the correct order) to a [concurrent.futures.ThreadPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor). Tasks that have a `parallelization_level` attribute are run in parallel on multiple threads.

Important: this is **multi-thread** parallelization, but probably to get mid-size workflows running on a powerful workstation we would need **multi-process** one. We would then need to play around with (concurrent.futures.ProcessPoolExecutor)[https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor]. Let's re-discuss about it.

> Another question I had about the process runner:
> Also, it appears to just be ignoring the executors I specified (or at least not complain that it doesn't have them specified).

This is expected.
1. Executors are always optional (even on the SLURM backend, where a default will be used if none is provided).
2. Executors only matter for the SLURM backend, while the `process` has no additional options (see above).

> I have now updated the splash page with a "How to Get Started" section and added READMEs containing the relevant information contained here on how to run the example with the process backend.

Great, thanks! I'll review it as soon as I have a bit of time ;)

**Comment by jluethi** [comment]
Thanks for the answers above @tcompa ! Makes sense!

I have no strong opinions on 1 vs 2 conda environments. 

It may be easier to have a single folder with server & client code for the example. Benefit of the current setup is that we're anyway maintaining the server example folder and the 01 example. Running them in `process` runner mode takes almost no new changes, which is very convenient! So I'm also fine with them staying apart and maybe be a bit easier to maintain going forward.

**Comment by tcompa** [comment]
Some small updates on the server (https://github.com/fractal-analytics-platform/fractal-server/pull/445 and others):
1. Clarified a bit that some requirements are optional, in https://fractal-analytics-platform.github.io/fractal-server/install_and_deploy/#preliminary-requirements.
2. Fixed a few broken links (let me know if you spot others).
3. General docs improvements here and there.

**Comment by jluethi** [comment]
Ok, I think all the stumbling blocks mentioned here are now covered in the documentation & the READMEs :)
