### ISSUE TITLE
Fractal server installation: Slurm option?

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-demos#27]
Running the current installation script for fractal-server 1.0.2 with pip install fractal-server[slurm]==1.0.2 results in `./install_script.sh:10: no matches found: fractal-server[slurm]==1.0.2`.

What is the slurm installation option adding? Do we still need it?

**Comment by jluethi** [comment]
I removed the slurm option with https://github.com/fractal-analytics-platform/fractal-demos/commit/d3166387da78f8d2094f220706c759832e4b063c to make the demo work for the moment (works at least for local server setup). I'm fine with this being added back (or having a local & slurm version) if needed for slurm (& working).

**Comment by tcompa** [comment]
The `slurm` extra installs the optional dependencies clusterfutures=0.5 (and cloudpickle). You can safely skip it if planning to use the local backend only.

However, I don't think this is the reason of the `no matches found error`. Providing an invalid extra only leads to a warning:
```
$ pip install fractal-server[xxx]==1.0.2
Collecting fractal-server[xxx]==1.0.2
  Using cached fractal_server-1.0.2-py3-none-any.whl (83 kB)
WARNING: fractal-server 1.0.2 does not provide the extra 'xxx'
...
```

My best guess for the `no matches found` error is that pip cache is out of date, and 1.0.2 was not available yet. We observe this quite often, when trying to install a package a minute after releasing it. I don't know how often pip cache is refreshed.

Anyway, you can always add `--no-cache-dir` to the `pip install` command.

**Comment by jluethi** [comment]
Hmm, interesting and good to know that we should have it for the slurm example.

I tried the `pip install fractal-server[slurm]==1.0.2 --no-cache-dir` and it fails with `zsh: no matches found: fractal-server[slurm]==1.0.2` (or the line above when run from the install script). 
Thus, somehow I don't get the warning, but the installation fails.

Can you install the slurm extras for fractal-server 1.0.2?

**Comment by tcompa** [comment]
> Can you install the slurm extras for fractal-server 1.0.2?

Yes
(but I use bash, not zsh - I will dig further)

**Comment by tcompa** [comment]
Here it is:
* https://stackoverflow.com/a/30539963/19085332

**Comment by jluethi** [comment]
Ah, right! I had forgotten about that again, napari does a similar thing. Added back the slurm extras in "" now, that works on zsh as well now.

Thanks @tcompa !
