### ISSUE TITLE
Update (some?) examples to tasks 0.9.0

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-demos#35]
See https://github.com/fractal-analytics-platform/fractal-tasks-core/blob/main/CHANGELOG.md#090, and notably

> * Rename task arguments: `ROI_table_name->input_ROI_table` and `bounding_box_ROI_table_name->output_ROI_table` (\#306).

**Comment by jluethi** [comment]
I've anyway been meaning to update more examples to the 1.1.0 server release (see list https://github.com/fractal-analytics-platform/fractal-demos/issues/29), will update to 0.9.0 task version as well :)

**Comment by jluethi** [comment]
All the core examples (besides example 03 with the multiplexing channel bug) are now updated to 1.1.0 server release candidates & 0.9.0 tasks :)

I'm closing this and tracking progress on the user_specific_examples at https://github.com/fractal-analytics-platform/fractal-demos/issues/36
