### ISSUE TITLE
Should fractal examples move to this repo? (+other suggestions)

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-demos#9]
The official fractal examples currently live on the client repo, and then they are somewhat linked to its version (but they are most of the time out of sync, since we update them only after client/server updates). They carry no information on the more general required environment (tasks/client/server versions).

1. What about moving this repo to `fractal-analytics-platform`, and hosting examples there? Having them on the client repo was meant to be because it is the "main" repo, but when all the user does it to pip-install it the examples are in no way easily accessible.
2. In each example folder, we should include whatever additional python script is needed (this is typically already the case), even if in the long-run there should be no additional python script at all. Moreover, most importantly, we should include a set of the three-packages versions used to successfully run an example. This could be a file like `VERSIONS` (in each example folder), with one or more lines like
```
fractal-client==0.2.0, fractal-server=1.2.5, fractal-tasks-core==3.2.1
```

**Comment by jluethi** [comment]
I like this idea. Was anyway thinking of transitioning this repo to the org. In that way, we can keep the client repo tighter and can be more free to update examples in the demo repo :)

I'll look into this

Also, great idea of specifying the versions that an example runs on!

**Comment by tcompa** [comment]
> I like this idea. Was anyway thinking of transitioning this repo to the org. In that way, we can keep the client repo tighter and can be more free to update examples in the demo repo :)

And we won't have all those "update examples" issues, which kinda interfere with the rest.

**Comment by jluethi** [comment]
We'll still have the issues, they'll just be in their own repository ;)
Updating examples will still remain something that needs to be done after all. But if you can show me in one example what has changed, I can manage & test the others :)

**Comment by tcompa** [comment]
Sure.
(I mean "interfere with the rest of the client issues", since updating the examples is different from updating the client)

**Comment by tcompa** [comment]
I did the same and succeeded:
![Screenshot from 2022-10-13 11-44-04](https://user-images.githubusercontent.com/3862206/195563217-0703497a-bf13-4e50-a9a7-449145ce3481.png)

https://github.com/fractal-analytics-platform/test

**Comment by tcompa** [comment]
I think you have a space at the beginning of the org name

**Comment by jluethi** [comment]
I moved all the examples. Let's discuss fractal versions here: https://github.com/fractal-analytics-platform/fractal-demos/issues/11
